### ISSUE TITLE
Flashing on a Wifi Dev Board?

### ISSUE THREAD

**Issue by dreamshape** [carvilsi/esp32-wifi-map#3]
Sorry i'm really new to this but 
I've been trying to flash it on my FZ wifi dev board but i get an error saying the image is for the chip esp32 whereas my board is an esp32s2; i i change the --chip parameters to esp32s2 and do --force it doesn't work on my flipper and idf.py set-target esp32s2 doesn't work either 

Is there any way to make it work with a wifi dev board or it is only for esp32 boards?

**Comment by carvilsi** [comment]
Hi @dreamshape,
You tried it with this [one](https://shop.flipperzero.one/products/wifi-devboard) right? Unfortunately I do not have one of those.  

> Is there any way to make it work with a wifi dev board or it is only for esp32 boards?

I only tested this with an **ESP32 ESP-WROOM-32** from this [company](https://www.az-delivery.de/en/products/esp32-dev-kit-c-unverlotet). So far as I know this only works on a **ESP32** and maybe the code will need some modifications in order to work on a **ESP32-S2**, do not know tho.

Checking the **FZ WiFi Dev Board** [documentation](https://docs.flipper.net/development/hardware/wifi-developer-board/update) seems that the flash process is quite different, although the firmware is built with **ESP-IDF** 

Sorry I could not help :woman_shrugging: 

Anyway, do not heist to send the flashing error log when changing the board `idf.py set-target esp32s2`.

**Comment by dreamshape** [comment]
> Hi @dreamshape, You tried it with this [one](https://shop.flipperzero.one/products/wifi-devboard) right? Unfortunately I do not have one of those.
> 
> > Is there any way to make it work with a wifi dev board or it is only for esp32 boards?
> 
> I only tested this with an **ESP32 ESP-WROOM-32** from this [company](https://www.az-delivery.de/en/products/esp32-dev-kit-c-unverlotet). So far as I know this only works on a **ESP32** and maybe the code will need some modifications in order to work on a **ESP32-S2**, do not know tho.
> 
> Checking the **FZ WiFi Dev Board** [documentation](https://docs.flipper.net/development/hardware/wifi-developer-board/update) seems that the flash process is quite different, although the firmware is built with **ESP-IDF**
> 
> Sorry I could not help 🤷‍♀️
> 
> Anyway, do not heist to send the flashing error log when changing the board `idf.py set-target esp32s2`.

thanks for the board link I might get one and try again (assuming I don't have to flash anything on the FZ if the latest .fap is already all set up)

I can try to see if I can get a log but usually when I tamper with sdk or do the set-target command off (or even esptool) detect the changes and takes it in account and rewrite the file 

if I set target to esp32s2 it just tells me there's an error that UART_2 is undefined and suggest to replace it with UART_1 but when I do that and try on the flipper it print me some error logs with the functions so I think a simple code edit won't help much

I've tried that on a Linux machine however for some reason I tried to follow a guide to make IDF.py run on wsl2 but I get a different kind of error the compilation goes well and all but when it's about to flash it gives me the error COM6 port not found despite it being properly connected and all 

but eh this is way above my skills so I'll try with an actual esp32 board

**Comment by carvilsi** [comment]
You are welcome.

Yep if you can get an **ESP32** board maybe it's better solution than trying to run it on **FZ WiFi Dev Board**, at least until you'll get more experience with it.

> if I set target to esp32s2 it just tells me there's an error that UART_2 is undefined and suggest to replace it with UART_1 but when I do that and try on the flipper it print me some error logs with the functions so I think a simple code edit won't help much

The `esp32-wifi-map` uses **UART_NUM_2** (TX2 GPIO_17) for the serial communication with **FZ**, if says something like **UART_2** is undefined, could be related with the configuration (or just the hardware it's different for **s2**). But I **guess** that what you see at the Flipper side should be the *console* output from *esp32-s2* and whatever it's running; so just with the **FZ WiFi Dev Board** connected to the computer and doing a `$ idf.py -p PORT monitor` *theoretically* you'll see same output.

**Comment by dreamshape** [comment]
I just got it to work with an esp32 and when I launch it it print 4 values like bxxxxxxxx;90.85;5;25 since it's a WIP i'm wondering atm what are the meaning of each of these values (aside first one)? are those like (x,y) points that would get printed on a graph map?

**Comment by dreamshape** [comment]
I actually managed to run it it's really cool! however between every screen update the screen goes blank a few seconds then print the updated map is that normal behaviour? 

more exactly goes like > flipper led blink green once > print screen > flipper led blink green again > empty screen > flipper blink gree > print updated screen and so on

**Comment by carvilsi** [comment]
Glad to know that you could run it :muscle: 
 
Yep the behavior that you describe is the normal one.

Contributions are very welcome :wink:

**Comment by FerdinandoPH** [comment]
> I actually managed to run it it's really cool! however between every screen update the screen goes blank a few seconds then print the updated map is that normal behaviour?
> 
> more exactly goes like > flipper led blink green once > print screen > flipper led blink green again > empty screen > flipper blink gree > print updated screen and so on

What did you replace `UART_NUM_2` with?

Edit: Nvm I replaced it with `UART_NUM_0` and it worked. I also ran the command `idf.py set-target esp32s2`
I don't know if the unleashed repository has an old version of the app or something, but I also had to rebuild the flipper app too
